### ISSUE TITLE
"non-web" is too vague

### ISSUE THREAD

**Issue by edysli** [SURFnet/nonweb-sso#1]
Please precisely define what you mean by "non-web". Does it mean the client is not a web browser? Does it mean communications do not happen over HTTP?

**Comment by joostd** [comment]
Yes indeed, it means the client is not a web browser. But communication does happen over HTTP. Typically, a RESTful API is used over HTTP.

**Comment by edysli** [comment]
Thanks for the precision! :smile: The client (mobile app) does however open a web browser to do the user authentication. :stuck_out_tongue_winking_eye:
